version: 0.1

phases:
  install:
    commands:
      - sudo yum update
      - sudo yum -y install python-setuptools
      - sudo yum -y install python-dev
      - sudo easy_install pip
      - pip install pycryptodome
      - pip install boto3
  build:
    commands:
      - echo Generating Key Pair...
      - python keygen.py
  
  post_build:
    commands:
      - echo Build completed on `date`