version: 0.1

phases:
  install:
    commands:
      - easy_install pip
      - pip install pycryptodome
      - pip install boto3

  build:
    commands:
      - echo Generating Key Pair...
      - python keygen.py
  
  post_build:
    commands:
      - echo Build completed